import { APPLICATION_STATUS } from "@/lib/constant";
import { TJob } from "./job";
import { Review } from "./reviews";
import { BlockList } from "net";

export interface TUser {
  _id: string;
  name: string;
  email: string;
  role: string | number;
  applicationStatus: keyof typeof APPLICATION_STATUS;
  password: string;
  phone: string;
  nidNumber: string;
  nidCopy: string;
  drivingLicense: string;
  drivingLicenseCopy: string;
  maxEducationLevel: string | number;
  maxEducationLevelCertificateCopy: string;
  chairmanCertificateCopy: string;
  portEntryPermitCopy: string;
  yearsOfExperience: string;
  address: string;
  division: string;
  district: string;
  profilePhoto: string;
  organizationType: string;
  organizationContactPerson: string;
  otpCode: string;
  deviceID: string;
  otpExpiry: Date;
  createdAt: Date;
  birthCertificate: string;
  portEntryPermit: string;
  updatedAt: Date;
  jobsApplied: TJob[];
  following: Array<string>;
  followers: Array<string>;
  reviews_for_employees: Array<string>;
  reviews_from_employers: Array<Review>;
  id: string;
  job: string;
  applicant: string;
  isAdmin: boolean;
  profession: string;
  nidPhoto: "";
  drivingLicensePhoto: "";
  isMobileUser: boolean;
  isDeleted: boolean;
  deletedAt: Date;
  isBanned: boolean;
  isVerified: boolean;
  lastOTPRequestTime: Date;
  otpRequestCount: number;
}
