import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import app_logo_black from "@/app/assets/logo-black.png";
import app_logo_white from "@/app/assets/logo-white.png";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function AuthLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="h-screen">
      <div className="w-full max-w-7xl mx-auto p-6">
        <div>
          <Link href="/">
            <Image
              src={app_logo_black}
              alt="App logo"
              className="h-[24px] inline-block dark:hidden"
            />
            <Image
              src={app_logo_white}
              alt="App logo"
              className="h-[24px] hidden dark:inline-block"
            />
          </Link>
        </div>
        {children}
      </div>
    </section>
  );
}

// bg-[url('./assets/auth-bg.jpg')] bg-no-repeat bg-center bg-cover
