import type { Metadata } from "next";
import { AppLogo } from "../assets/AppLogo";

export const metadata: Metadata = {
  title: "Nibay",
  description: "Generated by create next app"
};

export default function AuthLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="h-screen">
      <div className="w-full max-w-7xl mx-auto p-6">
        <div>
          <AppLogo />
        </div>
        {children}
      </div>
    </section>
  );
}

// bg-[url('./assets/auth-bg.jpg')] bg-no-repeat bg-center bg-cover
