export const USER_ROLE = {
  0: "CHECKER",
  1: "COUNTER_MASTER",
  2: "DRIVER",
  3: "FOREMAN",
  4: "GM",
  5: "HELPER",
  6: "MANAGER",
  7: "MECHANIC_MISTRY",
  8: "SUPERVISOR_PASSENGER_GUIDE",
  9: "TRUCK_DRIVER",
  10: "INSTITUTION",
  11: "INDIVIDUAL",
  12: "USER"
};

export type ROLE =
  | "INSTITUTION"
  | "INDIVIDUAL"
  | "USER"
  | "CHECKER"
  | "COUNTER_MASTER"
  | "DRIVER"
  | "FOREMAN"
  | "GM"
  | "HELPER"
  | "MANAGER"
  | "MECHANIC_MISTRY"
  | "SUPERVISOR_PASSENGER_GUIDE"
  | "TRUCK_DRIVER";

export const MAX_EDUCATION_LEVEL = {
  0: "ALIM",
  1: "BACHELOR",
  2: "HAFIZ",
  3: "HIGHER_SECONDARY",
  4: "JUNIOR_SECONDARY",
  5: "MASTER",
  6: "NO_FORMAL_EDUCATION",
  7: "PRIMARY",
  8: "SECONDARY"
};
