export const USER_ROLE = {
  INSTITUTION: "INSTITUTION",
  INDIVIDUAL: "INDIVIDUAL",
  USER: "USER",
  CHECKER: "CHECKER",
  COUNTER_MASTER: "COUNTER_MASTER",
  DRIVER: "DRIVER",
  FOREMAN: "FOREMAN",
  GM: "GM",
  HELPER: "HELPER",
  MANAGER: "MANAGER",
  MECHANIC_MISTRY: "MECHANIC_MISTRY",
  SUPERVISOR_PASSENGER_GUIDE: "SUPERVISOR_PASSENGER_GUIDE",
  TRUCK_DRIVER: "TRUCK_DRIVER"
};

export type ROLE =
  | "INSTITUTION"
  | "INDIVIDUAL"
  | "USER"
  | "CHECKER"
  | "COUNTER_MASTER"
  | "DRIVER"
  | "FOREMAN"
  | "GM"
  | "HELPER"
  | "MANAGER"
  | "MECHANIC_MISTRY"
  | "SUPERVISOR_PASSENGER_GUIDE"
  | "TRUCK_DRIVER";
